server:
  port: 8002
  
spring:
  application:
    name: goods-provider        #设置当前应用（微服务)的名字
  datasource:                                 #设置数据源信息
    type: com.alibaba.druid.pool.DruidDataSource   #设置数据库连接池的类型
    driver-class-name: org.gjt.mm.mysql.Driver    #设置数据库的驱动
    url: jdbc:mysql://127.0.0.1:3306/yz     #设置数据库的URL
    username: root
    password: 123456
    dbcp2:                                    
      min-idle: 5                             #设置最小连接池
      initial-size: 5                         #设置当前数据库连接池启动时，创建的连接数
      max-total: 10                           #设置最大连接池
      max-wait-millis: 2000                   #设置最大的等待时间  

mybatis:  mapper-locations:  - classpath:mapper/*.xml                         #设置Mybatis的Mapper.xml文件  type-aliases-package: com.springcloud.entity     #设置Mybatis实体类位置  configuration:    map-underscore-to-camel-case: true              #开启Mybatis驼峰命名规则
    
    
pagehelper:  helper-dialect: mysql                            #设置数据库
  reasonable: true                                 #设置分页合理化参数
  support-methods-arguments: true   
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/                  